version: 3
workdir: internal

excludeFiles:
  - "^.*_test\\.go$"
  - "^.*\/test\/.*$"

allow:
  depOnAnyVendor: false

vendors:
  cobra:           { in: github.com/spf13/cobra }
  color:           { in: github.com/fatih/color }
  godotenv:        { in: github.com/joho/godotenv }
  logrus:          { in: github.com/sirupsen/logrus }
  mongo:           { in: go.mongodb.org/mongo-driver/mongo }
  mongo-bson:      { in: go.mongodb.org/mongo-driver/bson/primitive }
  mongo-options:   { in: go.mongodb.org/mongo-driver/mongo/options }
  yaml:            { in: gopkg.in/yaml.v3 }

components:
  common:          { in: common/* }

  # Contrust
  cli:             { in: cli/ }

  # Contrustd
  server:          { in: server/ }
  database:        { in: server/mongodb/ }
  repo:            { in: server/repo/ }
  scenario:        { in: server/scenario/ }
  request:         { in: server/request/ }
  routes:          { in: server/routes/ }
  constants:       { in: server/constants/ }
  errors:          { in: server/local_errors/ }

commonComponents:
  - common
  - constants
  - errors

deps:
  common:
    canUse:
      - logrus

  # Contrust
  cli:
    canUse:
      - cobra
      - color
      - yaml

  # Contrustd
  server:
    mayDependOn:
      - database
      - routes
    canUse:
      - godotenv
  routes:
    mayDependOn:
      - request
      - scenario
  scenario:
    mayDependOn:
      - repo
      - request
  repo:
    mayDependOn:
      - database
    canUse:
      - mongo       # todo
  database:
    canUse:
      - mongo
      - mongo-options
      - mongo-bson
